version: '3.1'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    env_file:
      - ./.env.development
    environment:
      - TZ=Asia/Seoul
    ports:
      - 5433:5432
    volumes:
      - .my_project/db_data:/var/lib/postgresql/data